# HoverChat v1.0
# uForge © 2021

global:
  chatFormat: '&a%iridiumskyblock_island_level% &8| {DISPLAYNAME} &8» &7{MESSAGE}'
  dateFormat: 'dd-MM-yyyy HH:mm:ss'

hoverMessage:
  active: true
  hoverText:
    - "&bSent: &e{DATE}"
    - "&auForge :)"